### ISSUE TITLE
Support for Spanish Transaction Tax

### ISSUE THREAD

**Issue by jmgomezpoveda** [pviotti/degiro-bookkeeper#115]
When buying stocks on the Spanish stock market, I see some charges marked as "Spanish Transaction Tax", such as:

> 31-07-2023,14:54,31-07-2023,INT.AIRL.GRP,ES0177542018,Spanish Transaction Tax,,EUR,-60.00,EUR,1588.17,asdfgasd-asdf-asdf-asdf-asdfgasdfgas

I don't think the software is currently counting these as taxes already paid elsewhere, or to reduce the profits (not sure where it fits).

**Comment by pviotti** [comment]
True, that kind of tax is not taken into account at the moment (simply because I never came across it in my account statement). Based on [this](https://www.degiro.co.no/helpdesk/tax/what-spanish-financial-transaction-tax-spanish-ftt) it seems its value is proportional to the transaction value.

I've drafted a PR to support it, simply by adding it to the amount of the transaction fees (which is not ideal because it'd end up in "Degiro fees" total, but not sure how else to categorize this at the moment) https://github.com/pviotti/degiro-bookkeeper/pull/121

I would need the complete (anonymized) set of rows of a transaction that exhibit this kind of tax to write a test for it.

**Comment by jmgomezpoveda** [comment]
Please find attached; I hope it helps: [Account-2023.csv](https://github.com/pviotti/degiro-bookkeeper/files/13328778/Account-2023.csv)
