### ISSUE TITLE
Exception thrown on latest export? 

### ISSUE THREAD

**Issue by JustinLawler** [pviotti/degiro-bookkeeper#85]
Hi - not sure if this is a bug or if I'm not providing correct format of CSV file, but getting below error when running.

```
% ./src/Degiro.Cli/bin/Debug/net6.0/dgbk ~/Downloads/Transactions.csv --year 2021
Error: Couldn't parse row 1 according to schema: Expecting DateTime in Value date, got AIRBNB INC-CLASS A
```

Example first-line of CSV file:

```
Date,Time,Product,ISIN,Reference,Venue,Quantity,Price,,Local value,,Value,,Exchange rate,Transaction and/or third,,Total,,Order ID
11-10-2022,16:09,AIRBNB INC-CLASS A,US0090661010,NDQ,BATS,-6,104.2000,USD,625.20,USD,644.87,EUR,0.9695,-1.00,EUR,643.87,EUR,***********
11-10-2022,13:43,SRC BBG COM ETF,IE00BD6FTQ80,LSE,XLON,-25,24.3000,USD,607.50,USD,624.23,EUR,0.9732,-3.00,EUR,621.23,EUR,***********
```

**Comment by pviotti** [comment]
Hi, it looks like you downloaded the `Transactions` CSV file, rather than the `Account statement` one. They have a different schema, that's why `dgbk` crashes. This tool uses the Account Statement because it provides more detailed information. HTH
![image](https://user-images.githubusercontent.com/1350095/201540537-277a346b-5161-4a46-9104-d3b9150a6a11.png)

**Comment by JustinLawler** [comment]
Ah thanks for that! :)  I see it in the Readme.md file now! Thanks for your great work :)
